export const defaultBeast = {
  name: "",
  cr: 0,
  size: "medium",
  type: "beast",
  attributes: { str: 10, dex: 10, con: 10, int: 10, wis: 10, cha: 10},
  saves: [],
  skills: [],
  expertise: [],
  hp: 10,
  ac: 10,
  profBonus: 2,
  actions: [],
  speed: 30,
  climbSpeed: 0,
  flySpeed: 0,
  swimSpeed: 0,
  senses: [],
  features: [],
};

export const defaultSaves = {
  str: 0,
  dex: 0,
  con: 0,
  int: 0,
  wis: 0,
  cha: 0,
};

export const defaultSkills = {
  acrobatics: 0,
  animalHandling: 0,
  arcana: 0,
  athletics: 0,
  deception: 0,
  history: 0,
  insight: 0,
  intimidation: 0,
  investigation: 0,
  medicine: 0,
  nature: 0,
  perception: 0,
  performance: 0,
  persuasion: 0,
  religion: 0,
  sleightOfHand: 0,
  stealth: 0,
  survival: 0,
};